version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: dbmysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=radarFitDB
    restart: 'always'
 